// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BPMOPMobile.iPad
{
	public partial class XemDinhKemView : UIViewController
	{
		public XemDinhKemView (IntPtr handle) : base (handle)
		{
		}
	}
}
