// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BPMOPMobileV1.iOS
{
	public partial class MainViewApp : UIViewController
	{
		public MainViewApp (IntPtr handle) : base (handle)
		{
		}
	}
}
