// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BPMOPMobileV1.iOS
{
	public partial class Users_cell : UITableViewCell
	{
		public Users_cell (IntPtr handle) : base (handle)
		{
		}
	}
}
